import * as THREE from 'three';
import {LoadSystem} from './LoadSystem.js';
import {AudioManager} from './AudioManager.js';
import {MobileControls} from './MobileControls.js';

export class CraneController {
  constructor({rig,cargo,cargos,physics,onStatus=()=>{}}){this.rig=rig;this.physics=physics;this.loads=new LoadSystem();this.audio=new AudioManager();this.onStatus=onStatus;this.slewVelocity=0;this.trolleyVelocity=0;this.hoistVelocity=0;this.joint=null;this.attached=false;this.activeLoad=null;const list=cargos||[{mesh:cargo,type:'rebar',label:'钢筋束',half:{x:1.08,y:.2,z:.26},attachY:.18}];this.cargos=list.map(spec=>({...spec,body:physics.createCargo(spec.mesh,{mass:this.loads.weight(spec.type),half:spec.half}),mass:this.loads.weight(spec.type)}));this.cargo=this.cargos[0].body?this.cargos[0]:null;const hookPos=rig.block.getWorldPosition(new THREE.Vector3());this.hookBody=physics.createKinematic(hookPos);this.sling=null;}
  smooth(current,target,response,dt){return THREE.MathUtils.lerp(current,target,1-Math.exp(-response*dt));}
  loadType(){return this.activeLoad?.type||this.nearestLoad()?.load.type||'rebar';}
  capacity(){return this.loads.canLift(this.loadType(),this.rig.trolleyX);}
  hookPoint(){return this.rig.block.getWorldPosition(new THREE.Vector3());}
  cargoPoint(load=this.activeLoad||this.cargo){if(!load)return new THREE.Vector3(999,999,999);const p=load.body.body.translation();return new THREE.Vector3(p.x,p.y+(load.attachY??.18),p.z);}
  nearestLoad(){const hook=this.hookPoint();let best=null;for(const load of this.cargos){if(load===this.activeLoad)continue;const distance=hook.distanceTo(this.cargoPoint(load));if(!best||distance<best.distance)best={load,distance};}return best;}
  riggingDistance(){return this.attached?this.hookPoint().distanceTo(this.cargoPoint()):(this.nearestLoad()?.distance??999);}
  canConnect(){return !this.attached&&this.riggingDistance()<.3;}
  connect(){const nearest=this.nearestLoad();if(!nearest||nearest.distance>=.3)return false;this.activeLoad=nearest.load;const load=this.capacity();if(!load.ok){this.onStatus(`⚠ ${this.activeLoad.label} 超出当前幅度载荷`);this.activeLoad=null;MobileControls.vibrate([35,40,35]);return false;}this.joint=this.physics.createRope(this.hookBody,this.activeLoad.body.body,.68);this.attached=true;this.rig.cargo=this.activeLoad.mesh;this.createSling();MobileControls.vibrate(18);return true;}
  disconnect(){if(!this.attached)return false;this.physics.removeJoint(this.joint);this.joint=null;this.attached=false;this.rig.cargo=null;this.activeLoad=null;if(this.sling){this.sling.removeFromParent();this.sling.geometry.dispose();this.sling.material.dispose();this.sling=null;}MobileControls.vibrate(16);return true;}
  createSling(){const geometry=new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(),new THREE.Vector3(0,-.7,0)]);this.sling=new THREE.Line(geometry,new THREE.LineBasicMaterial({color:'#252b2a'}));this.rig.block.add(this.sling);}
  updateVisualCable(){const L=this.rig.cableLength;for(const cable of this.rig.cables){cable.scale.y=L/4.7;cable.position.y=-L/2;}this.rig.block.position.y=-L;}
  update(input,dt){const mass=this.activeLoad?.mass||0,loadFactor=this.attached?Math.max(.28,1-mass/8200):1;this.slewVelocity=this.smooth(this.slewVelocity,input.slew*.42*loadFactor,2.1*loadFactor,dt);this.trolleyVelocity=this.smooth(this.trolleyVelocity,input.trolley*1.65*loadFactor,3.2*loadFactor,dt);const lift=this.capacity(),requested=input.hoist>0&&this.attached&&!lift.ok?0:input.hoist;this.hoistVelocity=this.smooth(this.hoistVelocity,requested*1.7*loadFactor,3.4*loadFactor,dt);this.rig.rotor.rotation.y+=this.slewVelocity*dt;this.rig.trolleyX=THREE.MathUtils.clamp(this.rig.trolleyX+this.trolleyVelocity*dt,1.25,8.1);if(this.rig.trolleyX===1.25||this.rig.trolleyX===8.1)this.trolleyVelocity=0;this.rig.trolley.position.x=this.rig.trolleyX;const maxCable=this.rig.height-.25;this.rig.cableLength=THREE.MathUtils.clamp(this.rig.cableLength-this.hoistVelocity*dt,1.1,maxCable);if(this.rig.cableLength===1.1||this.rig.cableLength===maxCable)this.hoistVelocity=0;this.updateVisualCable();this.rig.root.updateMatrixWorld(true);this.hookBody.setNextKinematicTranslation(this.hookPoint());this.physics.step(dt);if(this.sling){const local=this.rig.block.worldToLocal(this.cargoPoint().clone());this.sling.geometry.setFromPoints([new THREE.Vector3(),local]);}this.audio.motor('crane',Math.max(Math.abs(this.slewVelocity),Math.abs(this.hoistVelocity)*.2,Math.abs(this.trolleyVelocity)*.3));}
  swingDeg(){if(!this.attached)return 0;const delta=this.cargoPoint().sub(this.hookPoint()),vertical=Math.abs(delta.y)||.001;return THREE.MathUtils.radToDeg(Math.atan2(Math.hypot(delta.x,delta.z),vertical));}
  snapshot(){const cap=this.capacity(),near=this.nearestLoad();return {physics:true,slewVelocity:this.slewVelocity,trolleyVelocity:this.trolleyVelocity,hoistVelocity:this.hoistVelocity,loadKg:this.attached?this.activeLoad.mass:0,loadType:this.activeLoad?.type||null,loadLabel:this.activeLoad?.label||near?.load.label||null,capacityKg:cap.capacity,swingDeg:this.swingDeg(),riggingDistance:this.riggingDistance(),cargoCount:this.cargos.length};}
  find(type='rebar'){return this.cargos.find(c=>c.type===type)||this.cargos[0];}
  debugPlaceCargo(position,type='rebar'){const load=this.find(type);load.body.body.setTranslation({x:position[0],y:position[1],z:position[2]},true);load.body.body.setLinvel({x:0,y:0,z:0},true);this.cargo=load;}
  debugPlaceCargoAtHook(type='rebar'){const p=this.hookPoint(),load=this.find(type);this.cargos.filter(c=>c!==load).forEach((c,i)=>c.body.body.setTranslation({x:-10+i*2,y:1,z:-8},true));this.debugPlaceCargo([p.x,p.y-(load.attachY??.18),p.z],type);}
}
