import * as THREE from 'three';
import {AudioManager} from './AudioManager.js';
import {MobileControls} from './MobileControls.js';

export class ExcavatorController {
  constructor({rig,physics,soil=[],truck,onDig=()=>{},onDump=()=>{}}){this.rig=rig;this.physics=physics;this.soil=soil;this.truck=truck;this.onDig=onDig;this.onDump=onDump;this.audio=new AudioManager();this.body=physics.createTrackedBody(rig.root,7200);this.velocity={left:0,right:0,boom:0,stick:0,bucket:0,slew:0};this.bucketLoad=0;this.truckLoad=0;this.fill=this.createBucketFill();}
  createBucketFill(){const group=new THREE.Group();for(let i=0;i<5;i++){const mesh=new THREE.Mesh(new THREE.DodecahedronGeometry(.12,0),new THREE.MeshStandardMaterial({color:'#78684d',roughness:1}));mesh.position.set(.05+i*.11,.02+(i%2)*.08,-.18+(i%3)*.16);mesh.castShadow=true;group.add(mesh);}group.visible=false;this.rig.bucket.add(group);return group;}
  smooth(value,target,response,dt){return THREE.MathUtils.lerp(value,target,1-Math.exp(-response*dt));}
  update(input,dt){const v=this.velocity;v.left=this.smooth(v.left,input.leftTrack*.72,2.2,dt);v.right=this.smooth(v.right,input.rightTrack*.72,2.2,dt);v.boom=this.smooth(v.boom,-input.rightY*.46,3,dt);v.bucket=this.smooth(v.bucket,-input.rightX*.58,3.4,dt);v.stick=this.smooth(v.stick,-input.leftY*.5,3,dt);v.slew=this.smooth(v.slew,-input.leftX*.42,2.8,dt);const forward=(v.left+v.right)*.5,turn=(v.right-v.left)*.44;const yaw=this.rig.root.rotation.y,dir=new THREE.Vector3(Math.cos(yaw),0,-Math.sin(yaw));const current=this.body.linvel();this.body.setLinvel({x:this.smooth(current.x,dir.x*forward,2,dt),y:current.y,z:this.smooth(current.z,dir.z*forward,2,dt)},true);this.body.setAngvel({x:0,y:turn,z:0},true);this.rig.upper.rotation.y+=v.slew*dt;this.moveJoint(this.rig.boom,v.boom,this.rig.limits.boom,dt);this.moveJoint(this.rig.stick,v.stick,this.rig.limits.stick,dt);this.moveJoint(this.rig.bucket,v.bucket,this.rig.limits.bucket,dt);this.syncBody();this.handleSoil(input,dt);this.audio.motor('tracks',Math.max(Math.abs(v.left),Math.abs(v.right)));this.audio.motor('hydraulic',Math.max(Math.abs(v.boom),Math.abs(v.stick),Math.abs(v.bucket),Math.abs(v.slew)));}
  moveJoint(node,velocity,limits,dt){node.rotation.z=THREE.MathUtils.clamp(node.rotation.z+velocity*dt,...limits);}
  syncBody(){const p=this.body.translation(),q=this.body.rotation();this.rig.root.position.set(p.x,p.y,p.z);this.rig.root.quaternion.set(q.x,q.y,q.z,q.w);this.rig.root.updateMatrixWorld(true);}
  bucketTip(){return this.rig.bucket.localToWorld(new THREE.Vector3(.55,-.16,0));}
  handleSoil(input,dt){const tip=this.bucketTip();if(this.bucketLoad<100&&input.rightX>.25&&this.rig.bucket.rotation.z<-.43){const candidates=this.soil.filter(c=>c.visible&&c.position.distanceTo(tip)<1.15);if(candidates.length){const chunk=candidates[0];chunk.visible=false;this.bucketLoad=Math.min(100,this.bucketLoad+25);this.fill.visible=true;this.fill.children.forEach((m,i)=>m.visible=i<this.bucketLoad/20);MobileControls.vibrate(12);this.onDig(this.bucketLoad);}}if(this.bucketLoad>0&&input.rightX<-.3&&this.rig.bucket.rotation.z>.1){const bed=this.truck.position.clone().add(new THREE.Vector3(.55,1.35,0));if(tip.distanceTo(bed)<2.1){this.truckLoad+=this.bucketLoad;this.bucketLoad=0;this.fill.visible=false;MobileControls.vibrate([18,35,18]);this.onDump(this.truckLoad);}}}
  snapshot(){return {physics:true,leftTrack:this.velocity.left,rightTrack:this.velocity.right,upperRotation:this.rig.upper.rotation.y,boomVelocity:this.velocity.boom,stickVelocity:this.velocity.stick,bucketVelocity:this.velocity.bucket,bucketLoad:this.bucketLoad,truckLoad:this.truckLoad,position:this.rig.root.position.toArray()};}
  debugPlaceSoilAtBucket(){this.rig.root.updateMatrixWorld(true);const p=this.bucketTip();const chunk=this.soil.find(c=>c.visible);if(chunk)chunk.position.copy(p);this.rig.bucket.rotation.z=-.65;return !!chunk;}
}
